filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/ads/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

logging:
  level: debug
  to_files: true
  files:
    path: /usr/share/filebeat/logs
    name: filebeat
    keepfiles: 7
    permissions: 0644
